# Generated by Django 5.1.6 on 2025-02-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bem',
            old_name='rfid_tag',
            new_name='numero_patrimonio',
        ),
        migrations.AddField(
            model_name='bem',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('descartado', 'Descartado')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj_cpf',
            field=models.CharField(default='00000000000000', max_length=18, unique=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_destino', to='core.departamento'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_origem', to='core.departamento'),
        ),
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bem')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
