# Generated by Django 5.1.6 on 2025-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_rfid_tag_bem_numero_patrimonio_bem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='rfid_tag',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
