# Generated by Django 5.1.6 on 2025-02-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bem_rfid_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logalteracao',
            name='bem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bem'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='bem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bem'),
        ),
    ]
