# Generated by Django 5.1.6 on 2025-03-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='instituicao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
