# Generated by Django 5.1.6 on 2025-04-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_hospede_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cama',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10),
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='ATIVA', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cama')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.hospede')),
            ],
        ),
    ]
