# Generated by Django 5.1.6 on 2025-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_hospede_cpf_alter_hospede_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(blank=True, default='Não informado', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='email',
            field=models.EmailField(blank=True, default='Não informado', max_length=254),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='endereco',
            field=models.TextField(blank=True, default='Não informado'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='instituicao',
            field=models.CharField(blank=True, default='Não informado', max_length=150),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='nome',
            field=models.CharField(blank=True, default='Não informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='telefone',
            field=models.CharField(blank=True, default='Não informado', max_length=20),
        ),
    ]
