# Generated by Django 5.1.6 on 2025-06-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADA', 'Ocupada')], default='DISPONIVEL', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='Não informado', max_length=100)),
                ('cpf', models.CharField(blank=True, default='Não informado', max_length=14, null=True)),
                ('email', models.EmailField(blank=True, default='Não informado', max_length=254)),
                ('telefone', models.CharField(blank=True, default='Não informado', max_length=20)),
                ('endereco', models.TextField(blank=True, default='Não informado')),
                ('instituicao', models.CharField(blank=True, default='Não informado', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='ATIVA', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cama')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.hospede')),
            ],
        ),
        migrations.AddField(
            model_name='cama',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='reservas.quarto'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.hospede')),
            ],
        ),
    ]
