# Generated by Django 5.1.6 on 2025-04-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_reserva_cama_alter_reserva_status_ocupacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
