# Generated by Django 5.1.6 on 2025-05-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoramento', '0013_relatoproblema_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=255)),
                ('carga_horaria', models.PositiveIntegerField(help_text='Carga horária em horas-aula')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lacunas', to='monitoramento.escola')),
            ],
            options={
                'verbose_name': 'Lacuna',
                'verbose_name_plural': 'Lacunas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProblemaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_usuarios', to='monitoramento.setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_reportados', to='monitoramento.greuser')),
            ],
            options={
                'verbose_name': 'Problema de Usuário',
                'verbose_name_plural': 'Problemas de Usuários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
