# Generated by Django 5.1.6 on 2025-06-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='avisos_imagens/')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='normal', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('visualizado', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.greuser')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_problemas', to='monitoramento.escola')),
                ('setor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.setor')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmacaoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('visualizado', 'Visualizado')], default='pendente', max_length=15)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='problemas.avisoimportante')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='monitoramento.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Lacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=255)),
                ('carga_horaria', models.PositiveIntegerField(help_text='Carga horária em horas-aula')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('R', 'Resolvidos'), ('E', 'Em Andamento')], default='P', max_length=1)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lacunas', to='monitoramento.escola')),
            ],
            options={
                'verbose_name': 'Lacuna',
                'verbose_name_plural': 'Lacunas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProblemaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('R', 'Resolvidos'), ('E', 'Em Andamento')], default='P', max_length=1)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='problemas/anexos/')),
                ('escola', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='monitoramento.escola')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_usuarios', to='monitoramento.setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_reportados', to='monitoramento.greuser')),
            ],
            options={
                'verbose_name': 'Problema de Usuário',
                'verbose_name_plural': 'Problemas de Usuários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
