# Generated by Django 5.1.6 on 2025-05-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0013_relatoproblema_escola'),
        ('problemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='normal', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.greuser')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_problemas', to='monitoramento.escola')),
                ('setor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.setor')),
            ],
        ),
    ]
