# Generated by Django 5.1.6 on 2025-07-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
        ('problemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemausuario',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='monitoramento.escola'),
        ),
        migrations.AlterField(
            model_name='problemausuario',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Em Andamento'), ('R', 'Resolvido')], default='P', max_length=1),
        ),
    ]
