# Generated by Django 5.1.6 on 2025-07-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0002_alter_problemausuario_escola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lacuna',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Em Andamento'), ('R', 'Resolvido')], default='P', max_length=1),
        ),
    ]
