# Generated by Django 5.1.6 on 2025-05-29 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0013_relatoproblema_escola'),
        ('problemas', '0002_avisoimportante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisoimportante',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.greuser'),
        ),
        migrations.AlterField(
            model_name='avisoimportante',
            name='setor_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.setor'),
        ),
    ]
