# Generated by Django 5.1.6 on 2025-05-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0013_relatoproblema_escola'),
        ('problemas', '0002_avisoimportante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisoimportante',
            name='setor_destino',
        ),
        migrations.AlterField(
            model_name='avisoimportante',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.greuser'),
        ),
        migrations.AlterField(
            model_name='avisoimportante',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoramento.escola'),
        ),
        migrations.AlterField(
            model_name='avisoimportante',
            name='prioridade',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
