# Generated by Django 5.1.6 on 2025-07-10 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
        ('problemas', '0003_alter_lacuna_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizacaoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_gestor', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_gestor', models.CharField(blank=True, max_length=20, null=True)),
                ('email_escola', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_gestor', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto_fachada', models.ImageField(blank=True, null=True, upload_to='fachadas_propostas/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('observacao_validacao', models.TextField(blank=True, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='monitoramento.escola')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
