# Generated by Django 5.1.6 on 2025-06-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0013_relatoproblema_escola'),
        ('problemas', '0003_alter_avisoimportante_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lacuna',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído'), ('A', 'Atrasado')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='problemausuario',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='monitoramento.escola'),
        ),
        migrations.AddField(
            model_name='problemausuario',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído'), ('A', 'Atrasado')], default='P', max_length=1),
        ),
    ]
