# Generated by Django 5.1.6 on 2025-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0004_lacuna_status_problemausuario_escola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lacuna',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('R', 'Resolvidos'), ('E', 'Em Andamento')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='problemausuario',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('R', 'Resolvidos'), ('E', 'Em Andamento')], default='P', max_length=1),
        ),
    ]
