# Generated by Django 5.1.6 on 2025-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0005_alter_lacuna_status_alter_problemausuario_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemausuario',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='problemas/anexos/'),
        ),
    ]
