# Generated by Django 5.1.6 on 2025-06-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0006_problemausuario_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisoimportante',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
