# Generated by Django 5.1.6 on 2025-06-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemas', '0007_avisoimportante_data_exclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisoimportante',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='avisos_imagens/'),
        ),
    ]
