# Generated by Django 5.1.6 on 2025-06-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0014_alter_resposta_resposta_sn'),
        ('problemas', '0008_avisoimportante_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacaoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='problemas.avisoimportante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.greuser')),
            ],
            options={
                'verbose_name': 'Visualização de Aviso',
                'verbose_name_plural': 'Visualizações de Avisos',
                'unique_together': {('aviso', 'usuario')},
            },
        ),
    ]
