# Generated by Django 5.1.6 on 2025-06-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0014_alter_resposta_resposta_sn'),
        ('problemas', '0009_visualizacaoaviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisoimportante',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConfirmacaoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('visualizado', 'Visualizado')], default='pendente', max_length=15)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='problemas.avisoimportante')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='monitoramento.escola')),
            ],
        ),
        migrations.DeleteModel(
            name='VisualizacaoAviso',
        ),
    ]
