# Generated by Django 5.1.6 on 2025-04-15 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('inep', models.CharField(max_length=20, unique=True)),
                ('email_escola', models.EmailField(max_length=254)),
                ('foto_fachada', models.URLField(blank=True, null=True)),
                ('legenda_foto', models.TextField(blank=True)),
                ('funcao_monitoramento', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GREUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.escola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('escolas_destino', models.ManyToManyField(blank=True, to='monitoramento.escola')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.IntegerField()),
                ('tipo_resposta', models.CharField(choices=[('SN', 'Sim/Não'), ('NU', 'Numérico'), ('TX', 'Texto')], default='SN', max_length=2)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('R', 'Resolvido'), ('U', 'Urgente')], default='P', max_length=1)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.escola')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.greuser')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.questionario')),
            ],
            options={
                'verbose_name_plural': 'Monitoramentos',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_sn', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=3, null=True)),
                ('resposta_num', models.FloatField(blank=True, null=True)),
                ('resposta_texto', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='respostas_fotos/')),
                ('monitoramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='monitoramento.monitoramento')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.setor')),
            ],
        ),
        migrations.CreateModel(
            name='RelatoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_adicional', models.TextField(blank=True)),
                ('data_relato', models.DateTimeField(auto_now_add=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('R', 'Resolvido'), ('U', 'Urgente')], default='P', max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='relatos_fotos/')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.greuser')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_responsavel', to='monitoramento.greuser')),
                ('tipo_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.tipoproblema')),
            ],
        ),
    ]
