# Generated by Django 5.1.6 on 2025-06-20 19:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('inep', models.CharField(max_length=20, unique=True)),
                ('email_escola', models.EmailField(max_length=254)),
                ('nome_gestor', models.CharField(max_length=255)),
                ('endereco', models.TextField(blank=True, help_text='Ex: Rua ABC, 123 - Bairro XYZ', verbose_name='Endereço da Escola')),
                ('foto_fachada', models.ImageField(blank=True, null=True, upload_to='escolas/fachadas/', verbose_name='Foto da Fachada')),
                ('email_gestor', models.EmailField(blank=True, help_text='Email oficial do gestor responsável', max_length=254, verbose_name='Email do Gestor')),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('telefone_gestor', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('escolas_destino', models.ManyToManyField(blank=True, to='monitoramento.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.IntegerField()),
                ('tipo_resposta', models.CharField(choices=[('SN', 'Sim/Não'), ('NU', 'Numérico'), ('TX', 'Texto')], default='SN', max_length=2)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('foto_comprovante', models.ImageField(blank=True, null=True, upload_to='monitoramentos/comprovantes/', verbose_name='Foto Comprobatória')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='monitoramento.escola')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoramentos', to=settings.AUTH_USER_MODEL)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='monitoramento.questionario')),
            ],
            options={
                'verbose_name_plural': 'Monitoramentos',
                'ordering': ['-criado_em'],
                'get_latest_by': 'criado_em',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_setores', to='monitoramento.setor')),
            ],
        ),
        migrations.AddField(
            model_name='questionario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.setor'),
        ),
        migrations.CreateModel(
            name='GREUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('nome_completo', models.CharField(blank=True, max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador do Sistema'), ('COORDENADOR', 'Coordenador GRE'), ('CHEFE_SETOR', 'Chefe de Setor'), ('MONITOR', 'Monitor Escolar'), ('ESCOLA', 'Escola'), ('CEDEPE', 'Técnico CEDEPE/Secretaria')], default='MONITOR', max_length=15, verbose_name='Tipo de Usuário')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('escolas', models.ManyToManyField(blank=True, related_name='usuarios', to='monitoramento.escola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoramento.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_sn', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True)),
                ('resposta_num', models.FloatField(blank=True, null=True)),
                ('resposta_texto', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('monitoramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='monitoramento.monitoramento')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='monitoramento.pergunta')),
            ],
            options={
                'unique_together': {('monitoramento', 'pergunta')},
            },
        ),
    ]
