# Generated by Django 5.1.6 on 2025-04-15 17:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greuser',
            name='escola',
        ),
        migrations.AddField(
            model_name='greuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='greuser',
            name='escolas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='monitoramento.escola'),
        ),
        migrations.AddField(
            model_name='greuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador do Sistema'), ('COORDENADOR', 'Coordenador GRE'), ('CHEFE_SETOR', 'Chefe de Setor'), ('MONITOR', 'Monitor Escolar'), ('GESTOR', 'Gestor da Escola'), ('CEDEPE', 'Técnico CEDEPE/Secretaria')], default='MONITOR', max_length=15, verbose_name='Tipo de Usuário'),
        ),
        migrations.AddField(
            model_name='relatoproblema',
            name='prioridade',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='relatoproblema',
            name='solucao_aplicada',
            field=models.TextField(blank=True, null=True, verbose_name='Solução Aplicada'),
        ),
        migrations.AddField(
            model_name='setor',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_setores', to='monitoramento.setor'),
        ),
        migrations.AlterField(
            model_name='greuser',
            name='celular',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato: (99) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')]),
        ),
    ]
