# Generated by Django 5.1.6 on 2025-04-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_remove_greuser_escola_greuser_cpf_greuser_escolas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='foto_fachada',
            field=models.ImageField(blank=True, null=True, upload_to='escolas/fachadas/', verbose_name='Foto da Fachada'),
        ),
    ]
