# Generated by Django 5.1.6 on 2025-04-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_alter_escola_foto_fachada'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='gestores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'GESTOR'}, related_name='escolas_gestoradas', to='monitoramento.greuser', verbose_name='Gestores da Escola'),
        ),
    ]
