# Generated by Django 5.1.6 on 2025-04-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_escola_gestores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='funcao_monitoramento',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='legenda_foto',
        ),
        migrations.AddField(
            model_name='escola',
            name='email_gestor',
            field=models.EmailField(blank=True, help_text='Email oficial do gestor responsável', max_length=254, verbose_name='Email do Gestor'),
        ),
        migrations.AddField(
            model_name='escola',
            name='endereco',
            field=models.TextField(blank=True, help_text='Ex: Rua ABC, 123 - Bairro XYZ', verbose_name='Endereço da Escola'),
        ),
    ]
