# Generated by Django 5.1.6 on 2025-04-23 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_remove_escola_funcao_monitoramento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escola', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escola',
            name='gestores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'ESCOLA'}, related_name='escolas_gestoradas', to='monitoramento.greuser', verbose_name='Usuários da Escola'),
        ),
        migrations.AlterField(
            model_name='greuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador do Sistema'), ('COORDENADOR', 'Coordenador GRE'), ('CHEFE_SETOR', 'Chefe de Setor'), ('MONITOR', 'Monitor Escolar'), ('ESCOLA', 'Escola'), ('CEDEPE', 'Técnico CEDEPE/Secretaria')], default='MONITOR', max_length=15, verbose_name='Tipo de Usuário'),
        ),
    ]
