# Generated by Django 5.1.6 on 2025-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0006_escola_user_alter_escola_gestores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='gestores',
        ),
        migrations.AddField(
            model_name='escola',
            name='nome_gestor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greuser',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
