# Generated by Django 5.1.6 on 2025-04-23 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0007_remove_escola_gestores_escola_nome_gestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato: (99) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='escola',
            name='telefone_gestor',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Celular deve estar no formato: (99) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')]),
        ),
    ]
