# Generated by Django 5.1.6 on 2025-04-29 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0008_escola_telefone_escola_telefone_gestor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'ordering': ['data_limite'], 'verbose_name_plural': 'Monitoramentos'},
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='data_limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='frequencia',
            field=models.CharField(choices=[('D', 'Diário'), ('S', 'Semanal'), ('Q', 'Quinzenal'), ('M', 'Mensal'), ('6', 'Semestral'), ('A', 'Anual')], default='S', max_length=1, verbose_name='Periodicidade'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='telefone_gestor',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
