# Generated by Django 5.1.6 on 2025-05-08 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0011_alter_escola_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'get_latest_by': 'criado_em', 'ordering': ['-criado_em'], 'verbose_name_plural': 'Monitoramentos'},
        ),
        migrations.RemoveField(
            model_name='monitoramento',
            name='data_envio',
        ),
        migrations.RemoveField(
            model_name='monitoramento',
            name='data_limite',
        ),
        migrations.RemoveField(
            model_name='monitoramento',
            name='data_resposta',
        ),
        migrations.RemoveField(
            model_name='monitoramento',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='monitoramento',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together={('monitoramento', 'pergunta')},
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='foto_comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='monitoramentos/comprovantes/', verbose_name='Foto Comprobatória'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='monitoramento.escola'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='monitoramento.questionario'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoramentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='monitoramento.pergunta'),
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='foto',
        ),
    ]
