# Generated by Django 5.1.6 on 2025-05-09 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0012_alter_monitoramento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoproblema',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoramento.escola'),
            preserve_default=False,
        ),
    ]
