# Generated by Django 5.1.6 on 2025-06-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0013_relatoproblema_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta_sn',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
    ]
