# Generated by Django 5.1.6 on 2025-06-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0014_alter_resposta_resposta_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproblema',
            name='setor',
        ),
        migrations.DeleteModel(
            name='RelatoProblema',
        ),
        migrations.DeleteModel(
            name='TipoProblema',
        ),
    ]
