# Generated by Django 5.1.6 on 2025-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='participantes',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='participantes',
            field=models.CharField(blank=True, help_text='Insira os nomes dos participantes separados por vírgula (opcional).', max_length=255, null=True),
        ),
    ]
