# Generated by Django 5.1.6 on 2025-04-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_agendamento_participantes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='salas',
            field=models.ManyToManyField(related_name='agendamentos', to='eventos.sala'),
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='sala',
        ),
    ]
